feat: model added with trained weights
Model added with trained weights saved. Training set consists of band1 data only. Possible error in preparing training data because of short training time (~5s per epoch). 

Error #1:
Unable to write predictions to .csv file
ValueError: setting an array element with a sequence